function escapeHtml(value = '') {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;');
}

export function renderPortfolio({ user, repos, theme }) {
  const title = `${user.name || user.login} — Portfolio`;
  const bio = user.bio || 'Developer, builder, and open-source enthusiast.';
  const repoCards = repos.map(repo => `
    <article class="card">
      <div class="card-top">
        <h3>${escapeHtml(repo.name)}</h3>
        <span>${escapeHtml(repo.language)}</span>
      </div>
      <p>${escapeHtml(repo.description)}</p>
      <div class="repo-meta">⭐ ${repo.stars} · 🍴 ${repo.forks}</div>
      <a href="${repo.url}" target="_blank" rel="noreferrer">View project →</a>
    </article>
  `).join('\n');

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(title)}</title>
  <link rel="stylesheet" href="./style.css" />
</head>
<body class="${theme === 'terminal' ? 'terminal' : ''}">
  <main>
    <section class="hero">
      <img src="${user.avatar_url}" alt="${escapeHtml(user.login)} avatar" />
      <p class="eyebrow">Generated by qassemfolio</p>
      <h1>${escapeHtml(user.name || user.login)}</h1>
      <p class="bio">${escapeHtml(bio)}</p>
      <div class="stats">
        <span>${user.public_repos} repos</span>
        <span>${user.followers} followers</span>
        <span>${user.following} following</span>
      </div>
      <div class="actions">
        <a href="${user.html_url}" target="_blank" rel="noreferrer">GitHub Profile</a>
        ${user.blog ? `<a href="${user.blog.startsWith('http') ? user.blog : `https://${user.blog}`}" target="_blank" rel="noreferrer">Website</a>` : ''}
      </div>
    </section>

    <section>
      <div class="section-title">
        <p>Selected work</p>
        <h2>Projects</h2>
      </div>
      <div class="grid">
        ${repoCards || '<p>No public repositories found.</p>'}
      </div>
    </section>
  </main>
</body>
</html>`;
}
